import type { User, Equipment, Booking, Notification } from "./types"

// Mock users for demonstration
export const mockUsers: User[] = [
  {
    id: "1",
    email: "farmer@example.com",
    name: "John Farmer",
    role: "farmer",
    phone: "+1234567890",
    location: "Iowa",
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "2",
    email: "owner@example.com",
    name: "Sarah Owner",
    role: "owner",
    phone: "+1234567891",
    location: "Nebraska",
    createdAt: new Date("2024-01-02"),
  },
  {
    id: "3",
    email: "admin@example.com",
    name: "Admin User",
    role: "admin",
    phone: "+1234567892",
    location: "Kansas",
    createdAt: new Date("2024-01-03"),
  },
]

// Mock equipment listings
export const mockEquipment: Equipment[] = [
  {
    id: "1",
    ownerId: "2",
    name: "John Deere 8R Tractor",
    category: "Tractor",
    description:
      "High-performance tractor suitable for large-scale farming operations. 370 HP engine with advanced precision agriculture technology.",
    pricePerDay: 450,
    images: ["/john-deere-tractor.jpg"],
    location: "Nebraska",
    availability: true,
    specifications: {
      "Engine Power": "370 HP",
      Year: "2022",
      "Fuel Type": "Diesel",
      Transmission: "AutoPowr",
    },
    createdAt: new Date("2024-02-01"),
  },
  {
    id: "2",
    ownerId: "2",
    name: "Case IH Combine Harvester",
    category: "Harvester",
    description:
      "Efficient combine harvester with 400 bushel grain tank capacity. Perfect for corn, wheat, and soybean harvesting.",
    pricePerDay: 850,
    images: ["/combine-harvester-field.png"],
    location: "Iowa",
    availability: true,
    specifications: {
      "Tank Capacity": "400 bushels",
      Year: "2023",
      "Header Width": "40 ft",
      "Engine Power": "473 HP",
    },
    createdAt: new Date("2024-02-05"),
  },
  {
    id: "3",
    ownerId: "2",
    name: "Kubota M7 Series Tractor",
    category: "Tractor",
    description: "Versatile mid-size tractor ideal for hay operations, livestock farming, and general field work.",
    pricePerDay: 280,
    images: ["/kubota-tractor.png"],
    location: "Kansas",
    availability: true,
    specifications: {
      "Engine Power": "170 HP",
      Year: "2023",
      "Fuel Type": "Diesel",
      Weight: "18,000 lbs",
    },
    createdAt: new Date("2024-02-10"),
  },
]

// Mock bookings
export const mockBookings: Booking[] = [
  {
    id: "1",
    equipmentId: "1",
    farmerId: "1",
    ownerId: "2",
    startDate: new Date("2024-03-15"),
    endDate: new Date("2024-03-20"),
    totalPrice: 2250,
    status: "confirmed",
    paymentStatus: "paid",
    createdAt: new Date("2024-03-01"),
  },
  {
    id: "2",
    equipmentId: "2",
    farmerId: "1",
    ownerId: "2",
    startDate: new Date("2024-04-01"),
    endDate: new Date("2024-04-05"),
    totalPrice: 4250,
    status: "pending",
    paymentStatus: "pending",
    createdAt: new Date("2024-03-25"),
  },
  {
    id: "3",
    equipmentId: "3",
    farmerId: "1",
    ownerId: "2",
    startDate: new Date("2024-02-10"),
    endDate: new Date("2024-02-15"),
    totalPrice: 1680,
    status: "completed",
    paymentStatus: "paid",
    createdAt: new Date("2024-02-01"),
  },
]

// Mock notifications
export const mockNotifications: Notification[] = [
  {
    id: "1",
    userId: "1",
    type: "booking",
    title: "Booking Confirmed",
    message: "Your booking for John Deere 8R Tractor has been confirmed by the owner.",
    read: false,
    createdAt: new Date("2024-03-01T10:30:00"),
    link: "/my-bookings",
  },
  {
    id: "2",
    userId: "1",
    type: "payment",
    title: "Payment Successful",
    message: "Your payment of $2,250 has been processed successfully.",
    read: false,
    createdAt: new Date("2024-03-01T09:15:00"),
    link: "/my-bookings",
  },
  {
    id: "3",
    userId: "1",
    type: "booking",
    title: "Booking Request Pending",
    message: "Your booking request for Case IH Combine Harvester is awaiting owner approval.",
    read: true,
    createdAt: new Date("2024-02-28T14:20:00"),
    link: "/my-bookings",
  },
  {
    id: "4",
    userId: "2",
    type: "booking",
    title: "New Booking Request",
    message: "John Farmer has requested to book your John Deere 8R Tractor.",
    read: false,
    createdAt: new Date("2024-03-01T08:45:00"),
    link: "/my-equipment",
  },
  {
    id: "5",
    userId: "2",
    type: "payment",
    title: "Payment Received",
    message: "You received $2,250 for the rental of John Deere 8R Tractor.",
    read: true,
    createdAt: new Date("2024-03-01T09:20:00"),
  },
  {
    id: "6",
    userId: "1",
    type: "system",
    title: "Welcome to FarmEquip",
    message: "Thank you for joining our platform. Start browsing equipment today!",
    read: true,
    createdAt: new Date("2024-01-01T12:00:00"),
  },
]
